### ISSUE TITLE
Minor Feedback

### ISSUE THREAD

**Issue by Dman757** [Herohtar/netlify-cms-oauth-firebase#1]
Just set this up and wanted to give a bit of feedback. It was all pretty seamless and well documented good work!

Minor detail I would suggest to add to this would be mentioning the `firebase-tools` as a prereq https://github.com/firebase/firebase-tools

Also you noted about the firebase pricing in the notes which was super useful. I had to have my firebase account setup under the `blaze - pay as you go` pricing tier https://firebase.google.com/pricing/

**Comment by Herohtar** [comment]
Thanks for the feedback! That's a good idea; I'll update the readme with that info.

Yeah, the nice thing about using the Blaze plan is that it still includes the free usage from the Spark plan, and you can configure a spending limit of $0/day as a safety net to prevent it from actually costing anything if you end up going over.

**Comment by Herohtar** [comment]
I added the info in #2.
