### ISSUE TITLE
need billing account?

### ISSUE THREAD

**Issue by bsde1234** [Herohtar/netlify-cms-oauth-firebase#12]
Hi your readme says the need of billing account. firebase spark and blaze is free now. still need billing account?

**Comment by Herohtar** [comment]
@bsde1234 Yes, a paid plan (and thus a billing account) is still required, which means this will only work on the Blaze plan now. Specifically, the OAuth2 API uses outbound networking with non-Google services, and the function itself uses the Node.js 10 runtime, both of which are only available in the Blaze plan. The Blaze plan is free up to the limits of the Spark plan, and you will be billed accordingly for any usage beyond that. See the [Firebase pricing](https://firebase.google.com/pricing) for details.

I'll have to update the readme to reflect that.
