### ISSUE TITLE
Local auth

### ISSUE THREAD

**Issue by RWOverdijk** [Herohtar/netlify-cms-oauth-firebase#3]
Hey! Dumb question perhaps, but how does this work exactly?

I want to provide my users with regular accounts (email+password), does that work with this? Can I use those firebase providers? Or does it need to be github/gitlab?

**Comment by Herohtar** [comment]
It's just an OAuth client that allows you to authenticate with NetlifyCMS using your GitHub account. You can't use it to provide accounts for your users or with Firebase or anything like that. You can read more about how the authentication for NetlifyCMS works on [their website](https://www.netlifycms.org/docs/authentication-backends/).

**Comment by RWOverdijk** [comment]
Yeah, I created this issue before reading that. I didn't realize there are two server side components in the mix.

Thanks
